### ISSUE TITLE
Poor IDE choice

### ISSUE THREAD

**Issue by mcandre** [visi-lang/visi#12]
I was excited to learn more about Visi until I read

> Visi will be self-hosted with a built-in IDE like Smalltalk.

This is exactly why I don't use Squeak or Pharo. I don't want to use _your_ editor, I want to be able to use any editor. And I want to `./hello.visi | anotherprogram`, something you can't do when a language is bundled in a horrible non-POSIX, non-CLI VM environment. The few benefits of a Squeak style VM pale in comparison to the loss in flexibility: What if I want to interface Visi with a Perl script? What if I want to run a Visi daemon on bootup?

Please consider using a normal command line environment, providing the IDE as an optional feature.

**Comment by sseveran** [comment]
From talking to @dpp and as someone who is extremely excited about visi yours would be a non-core use case. You could certainly use visi to run a script but the point of visi and visi.pro as I understand it is to build a kind of an extended excel++. Today many people build quite sophisticated spreadsheets in excel using its shall we say, limited, tool set. The dream of visi is to allow non-developers (you are a real developer) to build visual applications that respond in real time to new data. Part of serving this market is making the development environment a core feature.

**Comment by dpp** [comment]
You're welcome to add whatever features you want to Visi.  The version I'm building will be self-hosted and not command-line.

Why?  Because I'm building a tool for people who are used to Excel or Dream Weaver or Eclipse.  Having command-line tools and Emacs and such leads to languages that are inconsistent with the goals of Visi.
